version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/app"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/tools/vis"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
